# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
