# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0003_visitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='time_stamp',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
