# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0006_visitrecord_is_crawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='update_stamp',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='visit_freq',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='visit_times',
            field=models.IntegerField(null=True),
        ),
    ]
