# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0007_auto_20170724_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='serially',
            field=models.IntegerField(null=True),
        ),
    ]
