# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0008_visitrecord_serially'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='reverse_deta',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
